### ISSUE TITLE
road map for migration new version!

### ISSUE THREAD

**Issue by HMarzban** [docs-plus/docs.plus#63]
- [x] Shout down the old Docsplus server
  - [x] Remove all Nginx configuration (maintain democracy pad)
  - [x] Remove `ws` subdomains
  - [x] Maintain the pm2 process list
  - [x] Remove and maintain project GitHub actions (delete unused and off-services project folders)
    - [x] Maintain Actions secrets and variables
- [x] Shout down the rocket chat server
- [x] Shout down the COTURN server
- [x] Remove `handbook.technology` nginx configuration, also from Digitalocean Domains
- [x] Use GitHub CI/CD flow (automate deployment)
  - [x] Remove old CI/CD server files and GitHub dependency settings (maintain democracy pad)
  - [x] Create a new CI/CD action flow (for stage and production)
- [x] Maintain Digitalocean space service (I just need to remove buckets for now)
- [x] Separate the development and production database, hocuspocus service
  - [x] Create a database service for the stage
  - [x] Create a database service for the production 
- [x] Separate the development and production supabase project services 
  - [x] Open a new and free supabase project and run the database migration for the stage
  - [x] Open a new and supabase project and run the database migration for the production
- [x] Reconfigure environment variable for production and stage 
  - [x] Create a new .env file as an example
